# Generated by Django 5.2.16 on 2026-07-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'factsofplants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackLabel',
        ),
    ]
