# Generated by Django 5.2.9 on 2026-01-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'mainofbd'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptype',
            name='care_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Уход за культурой'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='expected_yield_max',
            field=models.FloatField(default=5.0, verbose_name='Макс. урожайность (т/га)'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='expected_yield_min',
            field=models.FloatField(default=1.0, verbose_name='Мин. урожайность (т/га)'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='harvest_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкции по сбору урожая'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='icon',
            field=models.CharField(default='🌱', max_length=10, verbose_name='Иконка (эмодзи)'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='moisture_max',
            field=models.IntegerField(default=60, verbose_name='Макс. влажность почвы (%)'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='moisture_min',
            field=models.IntegerField(default=20, verbose_name='Мин. влажность почвы (%)'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='nitrogen_requirement',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10, verbose_name='Потребность в азоте (N)'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='ph_max',
            field=models.FloatField(default=7.5, verbose_name='Макс. pH почвы'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='ph_min',
            field=models.FloatField(default=6.0, verbose_name='Мин. pH почвы'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='phosphorus_requirement',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10, verbose_name='Потребность в фосфоре (P)'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='planting_depth_cm',
            field=models.FloatField(default=3.0, verbose_name='Глубина посадки (см)'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='planting_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкции по посадке'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='planting_season',
            field=models.CharField(choices=[('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень'), ('winter', 'Зима'), ('any', 'Любой')], default='spring', max_length=20, verbose_name='Сезон посадки'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='potassium_requirement',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10, verbose_name='Потребность в калии (K)'),
        ),
        migrations.AddField(
            model_name='croptype', 
            name='row_spacing_cm',
            field=models.IntegerField(default=50, verbose_name='Расстояние между рядами (см)'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='spacing_cm',
            field=models.IntegerField(default=30, verbose_name='Расстояние между растениями (см)'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='temp_min',
            field=models.FloatField(default=5.0, verbose_name='Мин. температура (°C)'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='temp_optimal',
            field=models.FloatField(default=20.0, verbose_name='Оптимальная температура (°C)'),
        ),
        migrations.AddField(
            model_name='croptype',
            name='vegetation_days',
            field=models.IntegerField(default=90, verbose_name='Период вегетации (дней)'),
        ),
    ]
