# Generated by Django 6.0.1 on 2026-01-10 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название участка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('bounds_json', models.TextField(verbose_name='Границы участка (JSON)')),
                ('center_lat', models.FloatField(verbose_name='Широта центра')),
                ('center_lon', models.FloatField(verbose_name='Долгота центра')),
                ('area_hectares', models.FloatField(default=0, verbose_name='Площадь (га)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeedDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_latin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Латинское название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('color_signature', models.TextField(blank=True, null=True, verbose_name='Цветовая сигнатура (JSON)')),
                ('texture_features', models.TextField(blank=True, null=True, verbose_name='Текстурные признаки (JSON)')),
                ('reference_images_json', models.TextField(blank=True, null=True, verbose_name='Референсные изображения (JSON)')),
                ('control_methods', models.TextField(blank=True, null=True, verbose_name='Методы борьбы')),
                ('danger_level', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=20, verbose_name='Уровень опасности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сорняк (база)',
                'verbose_name_plural': 'Сорняки (база)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название культуры')),
                ('name_latin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Латинское название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('min_return_interval', models.IntegerField(default=2, verbose_name='Мин. интервал возврата (лет)')),
                ('color', models.CharField(default='#4CAF50', max_length=7, verbose_name='Цвет')),
                ('bad_predecessors', models.ManyToManyField(blank=True, related_name='bad_successors', to='api.croptype', verbose_name='Плохие предшественники')),
                ('good_predecessors', models.ManyToManyField(blank=True, related_name='good_successors', to='api.croptype', verbose_name='Хорошие предшественники')),
            ],
            options={
                'verbose_name': 'Тип культуры',
                'verbose_name_plural': 'Типы культур',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackLabel', 
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(choices=[('fertility', 'Плодородие'), ('crop', 'Культура'), ('weed', 'Сорняк'), ('disease', 'Болезнь')], max_length=50, verbose_name='Тип маркировки')),
                ('label_value', models.CharField(max_length=100, verbose_name='Значение')),
                ('bbox_json', models.TextField(verbose_name='Область (JSON)')),
                ('point_lat', models.FloatField(verbose_name='Широта точки')),
                ('point_lon', models.FloatField(verbose_name='Долгота точки')),
                ('image_crop_base64', models.TextField(blank=True, null=True, verbose_name='Фрагмент изображения')),
                ('user_confidence', models.CharField(choices=[('low', 'Неуверен'), ('medium', 'Возможно'), ('high', 'Уверен')], default='medium', max_length=20, verbose_name='Уверенность')),
                ('used_for_training', models.BooleanField(default=False, verbose_name='Использовано для обучения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_labels', to='api.field', verbose_name='Поле')),
            ],
            options={
                'verbose_name': 'Маркировка обратной связи',
                'verbose_name_plural': 'Маркировки обратной связи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvasiveSpeciesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=255, verbose_name='Название вида')),
                ('species_type', models.CharField(choices=[('weed', 'Сорняк'), ('pest', 'Вредитель'), ('disease', 'Болезнь'), ('other', 'Другое')], default='weed', max_length=50, verbose_name='Тип')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='low', max_length=20, verbose_name='Степень заражения')),
                ('location_lat', models.FloatField(verbose_name='Широта')),
                ('location_lon', models.FloatField(verbose_name='Долгота')),
                ('affected_area', models.FloatField(default=0, verbose_name='Площадь поражения (м²)')),
                ('image_base64', models.TextField(blank=True, null=True, verbose_name='Изображение')),
                ('status', models.CharField(choices=[('detected', 'Обнаружено'), ('confirmed', 'Подтверждено'), ('treating', 'В обработке'), ('resolved', 'Устранено')], default='detected', max_length=20, verbose_name='Статус')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обнаружения')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата устранения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invasive_reports', to='api.field', verbose_name='Поле')),
            ],
            options={
                'verbose_name': 'Отчёт об инвазивных видах',
                'verbose_name_plural': 'Отчёты об инвазивных видах',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SoilAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата анализа')),
                ('bbox_json', models.TextField(verbose_name='BBOX (JSON)')),
                ('very_high_percent', models.FloatField(default=0, verbose_name='Очень высокое (%)')),
                ('high_percent', models.FloatField(default=0, verbose_name='Высокое (%)')),
                ('moderate_percent', models.FloatField(default=0, verbose_name='Умеренное (%)')),
                ('low_percent', models.FloatField(default=0, verbose_name='Низкое (%)')),
                ('non_fertile_percent', models.FloatField(default=0, verbose_name='Неплодородная (%)')),
                ('fertility_index', models.FloatField(default=0, verbose_name='Индекс плодородия')),
                ('overlay_image', models.TextField(blank=True, null=True, verbose_name='Маска плодородия')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.field', verbose_name='Поле')),
            ],
            options={
                'verbose_name': 'Анализ почвы',
                'verbose_name_plural': 'Анализы почвы',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='CropRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('season', models.CharField(choices=[('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень'), ('winter', 'Зима')], default='spring', max_length=20, verbose_name='Сезон')),
                ('yield_amount', models.FloatField(blank=True, null=True, verbose_name='Урожайность (т/га)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.croptype', verbose_name='Культура')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='api.field', verbose_name='Поле')),
            ],
            options={
                'verbose_name': 'Запись севооборота',
                'verbose_name_plural': 'Записи севооборота',
                'ordering': ['-year', '-created_at'],
                'unique_together': {('field', 'year', 'season')},
            },
        ),
        migrations.CreateModel(
            name='GrowthMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(verbose_name='Дата наблюдения')),
                ('ndvi_mean', models.FloatField(blank=True, null=True, verbose_name='Средний NDVI')),
                ('ndvi_min', models.FloatField(blank=True, null=True, verbose_name='Минимальный NDVI')),
                ('ndvi_max', models.FloatField(blank=True, null=True, verbose_name='Максимальный NDVI')),
                ('moisture_index', models.FloatField(blank=True, null=True, verbose_name='Индекс влажности')),
                ('health_score', models.FloatField(blank=True, null=True, verbose_name='Оценка здоровья')),
                ('growth_stage', models.CharField(blank=True, choices=[('bare_soil', 'Голая почва'), ('emergence', 'Всходы'), ('vegetative', 'Вегетация'), ('flowering', 'Цветение'), ('maturation', 'Созревание'), ('harvest', 'Уборка')], max_length=50, null=True, verbose_name='Стадия роста')),
                ('ndvi_overlay', models.TextField(blank=True, null=True, verbose_name='Маска NDVI')),
                ('data_source', models.CharField(choices=[('sentinel2', 'Sentinel-2'), ('landsat8', 'Landsat-8'), ('local_analysis', 'Локальный анализ'), ('manual', 'Ручной ввод')], default='local_analysis', max_length=50, verbose_name='Источник данных')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='api.field', verbose_name='Поле')),
            ],
            options={
                'verbose_name': 'Запись мониторинга роста',
                'verbose_name_plural': 'Записи мониторинга роста',
                'ordering': ['-observation_date'],
                'unique_together': {('field', 'observation_date')},
            },
        ),
    ]
